version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src/
      - node_modules:/app/node_modules
    networks:
      - common-net
volumes:
    node_modules:
networks:
  common-net:
    external:
      name: keycloaktest_net